
SUB_DEPTH = .
include $(KBUILD_PATH)/subheader.kmk

include $(PATH_CURRENT)/libsunshine/Makefile.kmk
include $(PATH_CURRENT)/xwintox/Makefile.kmk
include $(PATH_CURRENT)/mcom_tox/Makefile.kmk
include $(PATH_CURRENT)/gui_fltk/Makefile.kmk
#include $(PATH_CURRENT)/xwintox/forthobj/Makefile.kmk

include $(FILE_KBUILD_SUB_FOOTER)
