
SUB_DEPTH = ..
include $(KBUILD_PATH)/subheader.kmk

PROGRAMS += xwintox

xwintox_TEMPLATE = XwinTox
xwintox_DEFS = XWVERS=\"DR0\"
xwintox_SOURCES = xwintox.c module/manager.c
xwintox_INCS = $(PATH_ROOT)/libsunshine/hdr\
		hdr \
		.
xwintox_LIBS = $(libsunshine_1_TARGET) $(libluaobj_1_TARGET)

include $(FILE_KBUILD_SUB_FOOTER)
