SUB_DEPTH = ..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += libluaobj

libluaobj_TEMPLATE = XwSTATIC
libluaobj_SOURCES = modLOBJ.cxx
libluaobj_INCS = $(PATH_ROOT)/libsunshine/hdr \
		$(PATH_ROOT)/xwintox/hdr \
		hdr \
		.
libluaobj_LIBS = $(libsunshine_1_TARGET) stdc++

include $(FILE_KBUILD_SUB_FOOTER)
