SUB_DEPTH = ..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += libfastobj

libfastobj_TEMPLATE = XwSTATIC
libfastobj_SOURCES = modFOBJ.cxx binop.cxx operator.cxx vm.cxx xwfmisc.xxx \
		word/array.cxx word/dict.cxx word/integer.cxx word/lambda.cxx \
		word/name.cxx word/real.cxx word/string.cxx
libfastobj_INCS = $(PATH_ROOT)/libsunshine/hdr \
		$(PATH_ROOT)/xwintox/hdr \
		hdr \
		.
libfastobj_LIBS = $(libsunshine_1_TARGET) stdc++

include $(FILE_KBUILD_SUB_FOOTER)
